#!/usr/bin/env python3
"""Generate files.ts for AgentBox deployment from Sphinx build output.

Walks the _build/site/ directory, base64-encodes every file, and writes
a TypeScript module that maps URL paths to Uint8Array content.

Usage:
    python3 scripts/gen_agentbox_files.py [--site-dir _build/site] [--out functions/<project>-doc/files.ts]
    python3 scripts/gen_agentbox_files.py --url-prefix /pkb --out ../site/functions/freeswitch-primer/pkb-files.ts
"""

import argparse
import base64
import os
import sys

SKIP_DIRS = {".doctrees", "_sources"}
SKIP_FILES = {".buildinfo", "objects.inv"}
SKIP_EXTENSIONS = {".pyc", ".pyo", ".map"}
# Static assets are identical across language builds; keep only /en/_static/
# and let index.ts rewrite /zh/_static/* -> /en/_static/*
DEDUP_STATIC_PREFIXES = {"zh/_static", "zh/_sphinx_design_static"}
REWRITE_EXTS = {".html", ".css", ".js", ".svg", ".xml"}
MAX_FILE_SIZE = 2 * 1024 * 1024  # 2 MB per source file
# AgentBox rejects any single deploy file over 8 MiB (8388608).
ABX_MAX_TS_BYTES = 7 * 1024 * 1024

DECODE_TS = """// Auto-generated by scripts/gen_agentbox_files.py — do not edit
// Embedded static files for AgentBox deployment

function decode(b64: string): Uint8Array {
  const bin = atob(b64);
  const arr = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) arr[i] = bin.charCodeAt(i);
  return arr;
}

export const FILES: Record<string, Uint8Array> = {
"""


def normalize_url_prefix(raw: str) -> str:
    p = (raw or "").strip()
    if not p:
        return ""
    if not p.startswith("/"):
        p = "/" + p
    return p.rstrip("/")


def rewrite_root_paths(data: bytes, url_prefix: str, rel: str) -> bytes:
    """Point root-absolute /en/ and /zh/ links at the mounted prefix."""
    if not url_prefix:
        return data
    ext = os.path.splitext(rel)[1].lower()
    if ext not in REWRITE_EXTS:
        return data
    try:
        text = data.decode("utf-8")
    except UnicodeDecodeError:
        return data
    for lang in ("en", "zh"):
        text = text.replace(f'"/{lang}/', f'"{url_prefix}/{lang}/')
        text = text.replace(f"'/{lang}/", f"'{url_prefix}/{lang}/")
        text = text.replace(f"(/{lang}/", f"({url_prefix}/{lang}/")
    return text.encode("utf-8")


def should_skip(rel_path: str) -> bool:
    parts = rel_path.split(os.sep)
    for part in parts:
        if part in SKIP_DIRS or part.startswith("."):
            return True
    basename = os.path.basename(rel_path)
    if basename in SKIP_FILES:
        return True
    _, ext = os.path.splitext(rel_path)
    if ext in SKIP_EXTENSIONS:
        return True
    norm = rel_path.replace(os.sep, "/")
    for prefix in DEDUP_STATIC_PREFIXES:
        if norm.startswith(prefix):
            return True
    return False


def collect_files(site_dir: str, url_prefix: str = "") -> dict[str, bytes]:
    entries: dict[str, bytes] = {}
    prefix = normalize_url_prefix(url_prefix)
    for root, _dirs, files in os.walk(site_dir):
        for fname in sorted(files):
            fpath = os.path.join(root, fname)
            rel = os.path.relpath(fpath, site_dir)
            if should_skip(rel):
                continue
            size = os.path.getsize(fpath)
            if size > MAX_FILE_SIZE:
                print(f"  SKIP (too large): /{rel} ({size} bytes)", file=sys.stderr)
                continue
            with open(fpath, "rb") as f:
                data = f.read()
            data = rewrite_root_paths(data, prefix, rel)
            rel_url = rel.replace(os.sep, "/")
            url_path = f"{prefix}/{rel_url}" if prefix else f"/{rel_url}"
            entries[url_path] = data
    return entries


def line_for(path: str, data: bytes) -> str:
    b64 = base64.b64encode(data).decode("ascii")
    return f'  "{path}": decode("{b64}"),\n'


def split_entries(
    entries: dict[str, bytes], max_ts_bytes: int
) -> list[list[tuple[str, bytes]]]:
    header_len = len(DECODE_TS.encode("utf-8")) + 2  # closing `};\n`
    chunks: list[list[tuple[str, bytes]]] = []
    current: list[tuple[str, bytes]] = []
    size = header_len
    for path in sorted(entries.keys()):
        data = entries[path]
        line_len = len(line_for(path, data).encode("utf-8"))
        if current and size + line_len > max_ts_bytes:
            chunks.append(current)
            current = []
            size = header_len
        if header_len + line_len > max_ts_bytes:
            print(
                f"Error: {path} encodes to {line_len} bytes; "
                f"exceeds --max-ts-bytes {max_ts_bytes}.",
                file=sys.stderr,
            )
            sys.exit(1)
        current.append((path, data))
        size += line_len
    if current:
        chunks.append(current)
    return chunks


def write_module(out_path: str, pairs: list[tuple[str, bytes]]) -> None:
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    with open(out_path, "w") as f:
        f.write(DECODE_TS)
        for path, data in pairs:
            f.write(line_for(path, data))
        f.write("};\n")
    size = os.path.getsize(out_path)
    if size > 8388608:
        print(
            f"Error: {out_path} is {size} bytes (AgentBox per-file limit 8388608).",
            file=sys.stderr,
        )
        sys.exit(1)
    print(f"Generated {out_path} ({len(pairs)} files, {size / 1024 / 1024:.1f} MB)")


def cleanup_chunks(out_path: str) -> None:
    stem, ext = os.path.splitext(out_path)
    if ext != ".ts":
        return
    dirname = os.path.dirname(out_path) or "."
    base = os.path.basename(stem)
    for name in os.listdir(dirname):
        if name.startswith(f"{base}-") and name.endswith(".ts"):
            os.remove(os.path.join(dirname, name))


def write_index(out_path: str, chunk_paths: list[str]) -> None:
    names = [os.path.splitext(os.path.basename(p))[0] for p in chunk_paths]
    aliases = [f"f{i}" for i in range(len(names))]
    with open(out_path, "w") as f:
        f.write("// Auto-generated by scripts/gen_agentbox_files.py — do not edit\n")
        for alias, name in zip(aliases, names):
            f.write(f'import {{ FILES as {alias} }} from "./{name}.ts";\n')
        f.write("\nexport const FILES: Record<string, Uint8Array> = Object.assign(\n")
        f.write("  {},\n")
        for alias in aliases:
            f.write(f"  {alias},\n")
        f.write(");\n")
    print(f"Generated index {out_path} ({len(chunk_paths)} chunks)")


def write_ts(entries: dict[str, bytes], out_path: str, max_ts_bytes: int) -> None:
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    cleanup_chunks(out_path)
    chunks = split_entries(entries, max_ts_bytes)
    if len(chunks) == 1:
        write_module(out_path, chunks[0])
        return
    stem, ext = os.path.splitext(out_path)
    chunk_paths = []
    for i, pairs in enumerate(chunks):
        chunk_path = f"{stem}-{i}{ext}"
        write_module(chunk_path, pairs)
        chunk_paths.append(chunk_path)
    write_index(out_path, chunk_paths)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--site-dir",
        default="_build/site",
        help="Sphinx bilingual build output directory (default: _build/site)",
    )
    parser.add_argument(
        "--out",
        default="functions/doc/files.ts",
        help="Output TypeScript file path",
    )
    parser.add_argument(
        "--url-prefix",
        default="",
        help="URL prefix for embedded keys (e.g. /pkb). Empty keeps /en/... paths.",
    )
    parser.add_argument(
        "--max-ts-bytes",
        type=int,
        default=ABX_MAX_TS_BYTES,
        help="Max generated .ts size (default 7 MiB; AgentBox limit is 8 MiB).",
    )
    args = parser.parse_args()

    if not os.path.isdir(args.site_dir):
        print(f"Error: site directory not found: {args.site_dir}", file=sys.stderr)
        print("Run 'make html-all' first to build the bilingual site.", file=sys.stderr)
        sys.exit(1)

    print(f"Scanning {args.site_dir} ...")
    entries = collect_files(args.site_dir, args.url_prefix)
    if not entries:
        print("Error: no files found to embed.", file=sys.stderr)
        sys.exit(1)

    write_ts(entries, args.out, args.max_ts_bytes)


if __name__ == "__main__":
    main()
